plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

# NOTE: Keep cops in ASCII order for maintainability

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
