# frozen_string_literal: true

D = Steep::Diagnostic

target :lib do
  signature "sig"
  signature "sig/generated"

  check "lib"

  library "yaml"
  library "psych"

  configure_code_diagnostics do |hash|
    hash[D::Ruby::UnknownConstant] = :hint
  end
end
