# frozen_string_literal: true

D = Steep::Diagnostic

target :lib do
  signature "sig"
  signature "../herb-core/sig"

  check "lib"

  configure_code_diagnostics(D::Ruby.default) do |hash|
    hash[D::Ruby::UnannotatedEmptyCollection] = :hint
  end
end
