plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

# NOTE: Keep cops in ASCII order for maintainability

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/SpecFilePathFormat:
  Exclude:
    - "**/spec/**/rules/html_*_spec.rb"
    - "**/spec/**/rules/erb_*_spec.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/StringLiterals:
  EnforcedStyle: double_quotes
