plugins:
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

# NOTE: Keep cops in ASCII order for maintainability

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

# Disabled: causes infinite loop with Layout/ExtraSpacing for single-attribute Data classes
Style/RbsInline/DataClassCommentAlignment:
  Enabled: false

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation
  Exclude:
    - "*/spec/**/*"

# rubocop-rbs_inline flags trailing #: annotations as redundant for one-liner
# shorthand methods (def method = expr) when the return type can be inferred
# from the expression. This conflicts with MissingTypeAnnotation which requires
# the annotation. Exclude rule files which commonly use this pattern.
Style/RbsInline/RedundantTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation
  Exclude:
    - "*/lib/**/rules/**/*"

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Naming/PredicateMethod:
  AllowedMethods:
    - autofix

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NamedSubject:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/StringLiterals:
  EnforcedStyle: double_quotes
