plugins:
  - rubocop-numbered-params
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

# NOTE: Keep cops in ASCII order for maintainability

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Naming/PredicateMethod:
  AllowedMethods:
    - autofix

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation
  Exclude:
    - "**/spec/**/*.rb"

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes
