inherit_from: ../.rubocop-common.yml

# Allow longer lines for documentation URL comments
Layout/LineLength:
  AllowedPatterns:
    - '^\s*#\s*@see\s+https://' # Allow @see documentation URLs to exceed line length
