# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in herb-lint.gemspec
gemspec

gem "herb-config", path: "../herb-config"
gem "herb-core", path: "../herb-core"

gem "irb"
gem "rake"
gem "rbs"
gem "rbs-inline"
gem "rspec"
gem "rubocop"
gem "rubocop-rake"
gem "rubocop-rspec"
gem "steep"
