# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in herb-lint.gemspec
gemspec

gem "herb-config", path: "../herb-config"
gem "herb-core", path: "../herb-core"
gem "herb-highlighter", path: "../herb-highlighter"
gem "herb-printer", path: "../herb-printer"

gem "factory_bot"
gem "irb"
gem "rake"
gem "rbs"
gem "rbs-inline"
gem "rspec"
gem "rubocop"
gem "rubocop-factory_bot"
gem "rubocop-numbered-params"
gem "rubocop-rake"
gem "rubocop-rbs_inline"
gem "rubocop-rspec"
gem "steep"
