# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in herb-core.gemspec
gemspec

gem "irb"
gem "rake"
gem "rbs"
gem "rbs-inline"
gem "rspec"
gem "rubocop"
gem "rubocop-rake"
gem "rubocop-rbs_inline", ">= 1.5.0.pre.1"
gem "rubocop-rspec"
gem "steep"
